"""create lecturer table

Revision ID: 42903e4eaac7
Revises: 
Create Date: 2023-06-05 09:56:31.727558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42903e4eaac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_head', sa.Boolean(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturer')
    # ### end Alembic commands ###
